![En tête general](https://raw.githubusercontent.com/PythonLycee/PyLyc/master/img/En_tete_general.png)


<i>© Copyright Franck CHEVRIER 2019-2022 https://www.python-lycee.com.</i><br>
<i>Les activités partagées sur <a href="https://capytale2.ac-paris.fr/web/accueil"><strong>Capytale</strong></a> sont sous licence <a href="https://creativecommons.org/licenses/by-sa/3.0/fr/">Creative Commons</a>.</i>

<span style="color: #9317B4"> Pour exécuter une saisie Python, sélectionner la cellule et valider avec </span><span style="color: #B317B4"><strong>SHIFT+Entrée</strong></span>.


<figure style="float: right;">
        <img src="https://raw.githubusercontent.com/PythonLycee/PyLyc/master/img/Reve_Mouton.gif">
</figure>

<h1 style="color:#1037A7; font-size:40px;">Les moutons</h1>
<h1 style="color:#1037A7; font-size:14px;">Introduction à l'étude d'une chaîne de Markov</h2>
<br><br>
<h1 style="color:red; font-size:40px;">(Corrigé)</h1>


### <span style="color:#1037A7">Sommaire</span>

<span style="color:#1037A7">0.</span> <a href="#0">Présentation de la situation étudiée et notations</a><br>
<span style="color:#1037A7">1.</span> <a href="#1">Graphe probabiliste et première étude algorithmique</a><br>
<span style="color:#1037A7">2.</span> <a href="#2">Étude matricielle</a><br>
<span style="color:#1037A7">3.</span> <a href="#3">Étude asymptotique</a><br>
<span style="color:#1037A7">4.</span> <a href="#4">Complément : Expressions explicites des suites</a><br>
<br><br>


## <span style="color:#1037A7" id="0">0. Présentation de la situation étudiée et notations</span>

<BLOCKQUOTE style="background-color:#CAD6F7">
Un berger, mathématicien et insomniaque de surcroit, rêve chaque nuit de son troupeau de moutons.<br><br>
Son pré est traversé par une barrière, qui sépare initialement son troupeau en deux groupes égaux.
Chaque nuit, 5% des moutons situés à gauche de la barrière sautent à droite et 8% des moutons situés à droite de la barrière sautent à gauche.<br><br>
La question qui le hante et l'empêche de dormir est de savoir, à long terme, quelle sera la répartition des moutons de part et d'autre de la barrière...
</BLOCKQUOTE>
    





Pour tout $n\in\mathbb{N}$, on notera $g_n$ et $d_n$ les proportions respectives de moutons, à gauche et à droite, au bout de $n$ nuits. $g_n$ et $d_n$ sont aussi les probabilités, pour un mouton quelconque, de se trouver à gauche et à droite, au bout de $n$ nuits.
<br><br>
<span style="color:#8B8B89"><strong>NB :</strong> Pour l’étude de cette situation, on suppose que le nombre de moutons est suffisamment important pour pouvoir conserver les valeurs décimales avec une précision arbitraire.</span>

## <span style="color:#1037A7" id="1">1. Graphe probabiliste et première étude algorithmique</span>

<BLOCKQUOTE style="float:right; font-size: 11px; background-color:#DEE6FB;">
        <strong style="color:#1037A7" >Vocabulaire :</strong><br>
    Le schéma proposé s'appelle un <strong>graphe probabiliste</strong>, et la situation étudiée est une <strong>chaîne de Markov.</strong><br> 
        Les <strong>sommets</strong> G et D correspondent à "gauche" et "droite".<br>
        Les <strong>arêtes</strong> qui relient les sommets sont <strong>pondérées</strong> par les probabilités correspondantes.<br>
        Ainsi, la somme des poids des arêtes issues d'un sommet vaut 1.     
</BLOCKQUOTE>    
<strong>1.1. Compléter le schéma ci-dessous à l'aide des arêtes et pondérations manquantes.</strong> 
<figure>
        <img src="https://raw.githubusercontent.com/PythonLycee/PyLyc/master/img/graphe_proba_ebauche_corrige.png">
</figure>



<strong>1.2. Préciser les valeurs de $g_0$ et $d_0$, et donner une relation liant $g_n$ et $d_n$ pour tout $n\in\mathbb{N}$.</strong> 

<br>
<span style="color:red;">
<ul>
    <li>$g_0=0,5$ et $d_0=0,5$ ;</li>
    <li>$\forall n \in \mathbb{N} ; g_n+d_n=1$</li>
</ul>
</span>

<strong>1.3. Écrire deux relations traduisant les mouvements de moutons, d'une nuit à l'autre.</strong> 

<br>
<span style="color:red;">
<ul>
    <li>$\forall n \in \mathbb{N} ; g_{n+1}=0,95g_n+0,08d_n$</li>
    <li>$\forall n \in \mathbb{N} ; d_{n+1}=0,05g_n+0,92d_n$</li>
</ul>
</span>

<strong>1.4. Tester les syntaxes Python ci-dessous. Que permettent-elles de calculer ?</strong> 

In [10]:
# Exécuter cette cellule

a,b = 0.5,0.5

a,b = 0.95*a+0.08*b,0.05*a+0.92*b

a,b

(0.515, 0.48500000000000004)

<strong>1.5. Écrire une fonction Python <mark style="font-family: Consolas; background-color:#E9ECF9">repartition</mark> qui reçoit <mark style="font-family: Consolas; background-color:#E9ECF9">n</mark> en argument et renvoie un couple de valeurs correspondant à $g_n$ et $d_n$.</strong><br><br>
$\quad\;\;$Aide : On pourra écrire une boucle et utiliser la syntaxe vue dans la question précédente.

In [11]:
# Écrire ici la fonction repartition

def repartition(n):
    a,b = 0.5,0.5
    for k in range(n):
        a,b = 0.95*a+0.08*b,0.05*a+0.92*b
    return a,b
    

<strong>1.6. Effectuer un appel à la fonction <mark style="font-family: Consolas; background-color:#E9ECF9">repartition</mark> pour évaluer la répartition des moutons de part et d'autre de la barrière au bout de 4 nuits.</strong><br><br>

In [12]:
# Effectuer ici l'appel à la fonction repartition

repartition(4)

(0.549281045, 0.45071895500000003)

## <span style="color:#1037A7" id="2">2. Étude matricielle</span>

<BLOCKQUOTE style="float:right; font-size: 11px; background-color:#DEE6FB;">
        <strong style="color:#1037A7" >Vocabulaire :</strong><br>
        On dit que $U_n$ est la matrice de distribution au rang $n$.<br>
        La matrice $A$ s'appelle la matrice de transition associée.
        </strong>
</BLOCKQUOTE>    

Au vu des relations obtenues dans la question 1.3, on dit que les suites $(g_n)_{n\geq0}$ et $(g_n)_{n\geq0}$ sont des suites récurrentes imbriquées.<br>
Pour tout $n\in\mathbb{N}$, on pose $U_n=\begin{pmatrix} g_n & d_n \end{pmatrix}$.



<strong>2.1. Traduire les expressions obtenues en 1.3 sous la forme $U_{n+1}=U_{n}A$, où $A$ est une matrice carrée que l'on précisera.</strong>

<br>
<span style="color:red;">
$U_{n+1}=U_{n}A$ avec $A = \begin{pmatrix} 0,95 & 0,05 \\ 0,08 & 0,92 \end{pmatrix}$.
</span>




<strong>2.2. Démontrer par récurrence que pour tout $n\in\mathbb{N}$, on a $U_n=U_0A^n$. </strong>

<br>
<span style="color:red;">
<ul>
    <li>$U_0A^0=U_0I_2=U_0$ donc la propriété est initialisée pour $n=0$ ;</li>
    <li>Supposons que pour un entier $n\in\mathbb{N}$, on a $U_n=U_0A^n$.<br>
        Alors $U_{n+1}=U_nA=U_0A^nA=U_0A^{n+1}$, ce qui prouve que la propriété est héréditaire.<br></li>
</ul>
</span>



<strong>2.3.a. Tester les syntaxes Python ci-dessous. Que permettent-elles de calculer ?</strong>

<br>
<span style="color:red;">
Les syntaxes permettent de définir les matrice $U_0$ et $A$.<br>
Le calcul effectué est $U_0A^2$, il correspond donc à la matrice $U_2$.
</span>



In [13]:
# Exécuter cette cellule
import numpy as np

U_0 = np.matrix([[0.5,0.5]])

A = np.matrix([[0.95,0.05],[0.08,0.92]])

U_0*A**2
    

matrix([[0.52805, 0.47195]])

<strong>$\quad$b. Effectuer une saisie Python pour retrouver, matriciellement, le résultat de la question 1.6.</strong>

In [14]:
# Effectuer ici la saisie

U_0*A**4 

matrix([[0.54928104, 0.45071896]])

<strong>$\quad$c. Écrire une fonction Python <mark style="font-family: Consolas; background-color:#E9ECF9">U</mark> qui reçoit <mark style="font-family: Consolas; background-color:#E9ECF9">n</mark> en argument et renvoie la matrice $U_n$.<br>$\quad\;\;\;$Retrouver ensuite le résultat de la question précédente à l'aide d'un appel à cette fonction.</strong>

In [15]:
# Écrire ici la fonction U

def U(n):
    U_0=np.matrix([[0.5,0.5]]) 
    A = np.matrix([[0.95,0.05],[0.08,0.92]])
    return U_0*A**n


In [16]:
# Effectuer ici l'appel à la fonction U
U(4)

matrix([[0.54928104, 0.45071896]])

<strong>$\quad$d. Effectuer des appels à la fonction <mark style="font-family: Consolas; background-color:#E9ECF9">U</mark> pour déterminer $U_{50}$, $U_{100}$ et $U_{1000}$.<br>$\quad\;\;\;$Que peut-on conjecturer, à long terme, concernant la répartition des moutons de part et d'autre de la barrière ?</strong>

<br>
<span style="color:red;">
On peut conjecturer qu'il y aura environ 61,5% des moutons à gauche de la barrière à long terme.
</span>



In [17]:
# Effectuer ici des appels à la fonction U
U(50)

matrix([[0.61527544, 0.38472456]])

In [18]:
U(100)

matrix([[0.61538451, 0.38461549]])

In [19]:
U(1000)

matrix([[0.61538462, 0.38461538]])

## <span style="color:#1037A7" id="3">3. Étude asymptotique</span>

<BLOCKQUOTE style="float:right; font-size: 11px; background-color:#DEE6FB;">
<strong style="color:#1037A7" >Vocabulaire :</strong><br>
La matrice $S$ ainsi définie est appelée matrice de <strong>distribution invariante</strong><br> (ou matrice de <strong>répartition stable</strong>).
</strong>
</BLOCKQUOTE>    

On souhaite déterminer une matrice $S = \begin{pmatrix} x & y \end{pmatrix}$ telle que :
<ul>
    <li>$x+y=1$</li>
    <li>$SA=S$</li>
</ul>



<strong>3.1. Démontrer qu'une matrice $S$ vérifie les conditions souhaitées si et seulement si le système $\begin{Bmatrix} 0,05x & - & 0,08y & = & 0 \\ x & + & y & = & 1  \end{Bmatrix}$ est vérifié.</strong>

<br>
<span style="color:red;">
$\begin{Bmatrix} x+y=1 \\ SA=S  \end{Bmatrix} \Longleftrightarrow \begin{Bmatrix} x + y = 1 \\ \begin{pmatrix} x & y \end{pmatrix}\begin{pmatrix} 0,95 & 0,05 \\ 0,08 & 0,92 \end{pmatrix}=\begin{pmatrix} x & y \end{pmatrix}  \end{Bmatrix}$<br><br>
$\quad\quad\quad\quad\quad\;\;\Longleftrightarrow \begin{Bmatrix} x & + & y & = & 1 \\ 0,95x & + & 0,08y & = & x \\ 0,05x & + & 0,92y & = & y       \end{Bmatrix}$<br><br>   
$\quad\quad\quad\quad\quad\;\;\Longleftrightarrow \begin{Bmatrix} x & + & y & = & 1 \\ -0,05x & + & 0,08y & = & 0 \\ 0,05x & - & 0,08y & = & 0       \end{Bmatrix}$<br><br>   
$\quad\quad\quad\quad\quad\;\;\Longleftrightarrow \begin{Bmatrix} 0,05x & - & 0,08y & = & 0 \\ x & + & y & = & 1  \end{Bmatrix}$
</span>

<strong>3.2. En déduire que la matrice $S$ cherchée est unique, et donner ses coefficients ainsi que des valeurs approchées de ces valeurs.<br>$\quad\;\;$Quelles valeurs semble-t-on retrouver ? Cette matrice dépend-t-elle de la distribution initiale $U_0$ ? </strong>


<br>
<span style="color:red;">
Après résolution du système (par combinaison, substitution ou par résolution matricielle), on obtient une unique solution $S=\begin{pmatrix} \frac{8}{13} & \frac{5}{13} \end{pmatrix} \approx \begin{pmatrix} 0,615 & 0,385 \end{pmatrix}$.<br>
Elle ne dépend pas de l'état initial puisque les coefficients de $U_0$ n'inverviennent pas dans les calculs.<br>
Les coefficients obtenus semblent être les valeurs obtenues en 2.3.d correspondant à la répartition des moutons à long terme.
</span>



<BLOCKQUOTE style="float:right; font-size: 11px; background-color:#DEE6FB;">
<strong style="color:#1037A7" >Prolongement : (admis)</strong><br>
Si $0<p<1$ et $0<q<1$, la matrice de transition associée au graphe probabiliste ci-dessous est $A = \begin{pmatrix} 1-p & p \\ q & 1-q \end{pmatrix}$.<br>
Il existe alors une unique matrice de distribution invariante qui est $ S = \begin{pmatrix} \frac{p}{p+q} & \frac{q}{p+q} \end{pmatrix}$.<br>
De plus, si on note $U_n$ la matrice de distriubution au rang $n$, alors on a $\displaystyle\lim\limits_{n \to +\infty}{U_n}=S$ (cette limite est donc indépendante de l'état initial $U_0$).
</BLOCKQUOTE>   

## <span style="color:#1037A7" id="4">4. Complément : Expressions explicites des suites </span>

<strong>4.1. À l'aide des relations obtenues dans les questions 1.2 et 1.3, donner une expression de $g_{n+1}$ en fonction de $g_n$.</strong>

<br>
<span style="color:red;">
$g_{n+1}=0,95g_n+0,08d_n$<br>
$\quad\;\;\;=0,95g_n+0,08(1-g_n)$<br>
$\quad\;\;\;=0,95g_n+0,08-0,08g_n$<br>
$\quad\;\;\;=0,87g_n+0,08$
</span>



<strong>4.2. Pour tout $n\in\mathbb{N}$, on pose $\displaystyle u_n=\frac{8}{13}-g_n$.<br>
$\quad\;\;$a. Démontrer que la suite $(u_n)_{n\geq0}$ est géométrique.<br>
$\quad\;\;$b. En déduire l'expression de $u_n$ en fonction de $n$, puis les expressions de $g_n$ et de $d_n$ en fonction de $n$.<br>
$\quad\;\;$c. Écrire des fonctions Python <mark style="font-family: Consolas; background-color:#E9ECF9">g</mark> et <mark style="font-family: Consolas; background-color:#E9ECF9">d</mark> qui reçoivent <mark style="font-family: Consolas; background-color:#E9ECF9">n</mark> en argument et renvoient respectivement les valeurs $g_n$ et $d_n$.<br> 
$\quad\quad\;\;$Tester pour $n=4$ et vérifier qu'on retrouve le résultat de la question 1.6.</strong>

<br>
<span style="color:red;">
a. $\displaystyle u_{n+1}=\frac{8}{13}-g_{n+1}$<br>
$\quad\quad\;\;\displaystyle=\frac{8}{13}-0,87g_n-0,08$<br>
$\quad\quad\;\;\displaystyle=\frac{8}{13}-0,87\left(\frac{8}{13}-u_n\right)-0,08$<br>
$\quad\quad\;\;\displaystyle=\frac{8}{13}-0,87\left(\frac{8}{13}-u_n\right)-0,08$<br>
$\quad\quad\;\;\displaystyle=\frac{8}{13}-0,87\times\frac{8}{13}+0,87u_n-0,08$<br>
$\quad\quad\;\;\displaystyle=0,13\times\frac{8}{13}+0,87u_n-0,08$<br>
$\quad\quad\;\;\displaystyle=0,87u_n$<br><br>
La suite $(u_n)_{n\geq0}$ est donc géométrique :
<ul>
    <li>de premier terme $u_0=\frac{8}{13}-g_0=\frac{8}{13}-\frac{1}{2}=\frac{3}{26}$ ;</li>
    <li>de raison $q=0,87$.</li>
</ul>
<br><br>
b. On en déduit donc que pour tout $n\in\mathbb{N}$ :
<ul>
    <li>$\displaystyle u_n=\frac{3}{26}\times0,87^n$ ;</li>
    <li>$\displaystyle g_n=\frac{8}{13}-u_n=\frac{8}{13}-\frac{3}{26}\times0,87^n$ ;</li>
    <li>$\displaystyle d_n=1-g_n=\frac{5}{13}+\frac{3}{26}\times0,87^n$ .</li>
</ul>
</span>


In [20]:
# Écrire ici les fonctions a et b

def g(n):
    return 8/13-3/26*0.87**n

def d(n):
    return 5/13+3/26*0.87**n # ou 1-a(n)


In [21]:
# Effectuer ici les appels aux fonctions

g(4)

0.5492810450000001

In [22]:
d(4)

0.45071895500000003

<strong>
$\quad\;\;$d. Déterminer les limites des suites $(g_n)_{n\geq0}$ et $(d_n)_{n\geq0}$. Conclure.</strong>

<br>
<br>
<span style="color:red;">
Comme $0\leq0,87<1$, on en déduit que :
<ul>
    <li>$\displaystyle\lim\limits_{n \to +\infty}{u_n}=0$</li>
    <li>$\displaystyle\lim\limits_{n \to +\infty}{g_n}=\frac{8}{13}$</li>
    <li>$\displaystyle\lim\limits_{n \to +\infty}{d_n}=\frac{5}{13}$</li>
</ul>
À long terme, huit moutons sur treize seront à gauche de la barrière, et cinq moutons sur treize seront à droite.
</span>

![Markov](https://raw.githubusercontent.com/PythonLycee/PyLyc/master/img/Andrei_Markov.jpg) 

<center><a href="https://fr.wikipedia.org/wiki/Andre%C3%AF_Markov_(math%C3%A9maticien)">Andreï Markov</a> (1856-1922) a donné son nom à l'étude des <a href="https://fr.wikipedia.org/wiki/Cha%C3%AEne_de_Markov">chaînes de Markov</a>.</center>

<i>© Copyright Franck CHEVRIER 2019-2022 https://www.python-lycee.com.</i><br>
<i>Les activités partagées sur <a href="https://capytale2.ac-paris.fr/web/accueil"><strong>Capytale</strong></a> sont sous licence <a href="https://creativecommons.org/licenses/by-sa/3.0/fr/">Creative Commons</a>.</i>
